name: Build
on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Publish
        run: dotnet publish TodoAppWpf.csproj --configuration Release -o published/

      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: todo-app-wpf
          path: published/
          compression-level: 9